export const CREATE_SNAP_REQUEST = 'CREATE_SNAP_REQUEST'
export const CREATE_SNAP_SUCCESS = 'CREATE_SNAP_SUCCESS'

export const GET_SNAP_REQUEST = 'GET_SNAP_REQUEST'
export const GET_SNAP_SUCCESS = 'GET_SNAP_SUCCESS'

export const INIT_SNAP_REQUEST = 'INIT_SNAP_REQUEST'
export const INIT_SNAP_SUCCESS = 'INIT_SNAP_SUCCESS'

export const VERIFY_SNAP_REQUEST = 'VERIFY_SNAP_REQUEST'
export const VERIFY_SNAP_SUCCESS = 'VERIFY_SNAP_SUCCESS'


export const RESET_STATE = 'RESET_STATE';

